server:
  port: 8181


ypfp:
  customer-name: yantriksbootcamp

streamer:
  inventory-source-topic: custom-inventory-update-feed
  inventory-target-topic: inventory-update-feed
  dlq-topic: dlq-feed
kafka:
  consumer:
    spring.json.trusted.packages: "*"
    spring.json.use.type.headers: false
    bootstrap.servers: localhost:9092
    group.id: custom-12
    auto.offset.reset: earliest
    enabled: true
    dlq-publish.enabled: true
    retry:
      limit: 1
      backoff:
        max: 15s
        initial: 10s
    commit.interval: 5s
  producer:
    bootstrap.servers: localhost:9092
    max.in.flight.requests.per.connection: 100
    acks: all
    enabled: true
common:
  services:
    url: http://localhost:8094
